/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthoringPanel: typeof import('./src/components/authoring/AuthoringPanel.vue')['default']
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    BufferOverlay: typeof import('./src/components/BufferOverlay.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CompassHUD: typeof import('./src/components/CompassHUD.vue')['default']
    GraphScene: typeof import('./src/components/scene/GraphScene.vue')['default']
    LayerPanel: typeof import('./src/components/LayerPanel.vue')['default']
    ModeIndicator: typeof import('./src/components/ModeIndicator.vue')['default']
    NodeAssetsExtension: typeof import('./src/components/node/extensions/NodeAssetsExtension.vue')['default']
    NodeBlockRenderer: typeof import('./src/components/node/NodeBlockRenderer.vue')['default']
    NodeConnectionsPage: typeof import('./src/components/node/NodeConnectionsPage.vue')['default']
    NodeDetailPanel: typeof import('./src/components/NodeDetailPanel.vue')['default']
    NodeEditorOverlay: typeof import('./src/components/NodeEditorOverlay.vue')['default']
    NodeExtensionOutlet: typeof import('./src/components/node/NodeExtensionOutlet.vue')['default']
    NodeFieldRenderer: typeof import('./src/components/node/NodeFieldRenderer.vue')['default']
    NodeHistoryPage: typeof import('./src/components/node/NodeHistoryPage.vue')['default']
    NodeLearningPage: typeof import('./src/components/node/NodeLearningPage.vue')['default']
    NodeNotesExtension: typeof import('./src/components/node/extensions/NodeNotesExtension.vue')['default']
    NodeSearch: typeof import('./src/components/NodeSearch.vue')['default']
    NodeSummaryRenderer: typeof import('./src/components/node/NodeSummaryRenderer.vue')['default']
    NodeViewerHeader: typeof import('./src/components/node/NodeViewerHeader.vue')['default']
    NodeViewerTabBar: typeof import('./src/components/node/NodeViewerTabBar.vue')['default']
    NoteTypePageRenderer: typeof import('./src/components/node/NoteTypePageRenderer.vue')['default']
    OverlayShell: typeof import('./src/components/ui/OverlayShell.vue')['default']
    PackLibraryOverlay: typeof import('./src/components/packs/PackLibraryOverlay.vue')['default']
    PackLibraryPane: typeof import('./src/components/packs/PackLibraryPane.vue')['default']
    ProgressOverlay: typeof import('./src/components/ProgressOverlay.vue')['default']
    ScrollArea: typeof import('./src/components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/ui/scroll-area/ScrollBar.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    Sheet: typeof import('./src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./src/components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./src/components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./src/components/ui/sheet/SheetTrigger.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
    WorldPickerOverlay: typeof import('./src/components/WorldPickerOverlay.vue')['default']
  }
}
