// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type CreateNodeInput = { title: string; layer_id: string; node_type: string; content_data: string | null; tags: string[]; weight: number }

export type Edge = { id: string; source_id: string; target_id: string; edge_type: string; weight: number; created_at: string }

export type EdgeRef = { id: string; target_id: string; edge_type: string; weight: number }

export type Layer = { id: string; name: string; display_order: number; created_at: string }

export type Node = { id: string; title: string; layer_id: string; node_type: string; content_type: string; content_data: string | null; tags: string[]; learned: boolean; weight: number; pos_x: number | null; pos_y: number | null; pos_z: number | null; 
/**
 * Outgoing edges — loaded in the same call, no second IPC round-trip needed.
 */
connections: EdgeRef[]; created_at: string }

const ARGS_MAP = { '':'{"create_edge":["source_id","target_id","edge_type"],"create_layer":["name","display_order"],"create_node":["input"],"delete_edge":["id"],"get_layers":[],"get_nodes":["layer_id"],"mark_learned":["id","learned"],"seed_sample_data":[],"update_node_position":["id","x","y","z"]}' }
export type Router = { "": {create_edge: (sourceId: string, targetId: string, edgeType: string) => Promise<Edge>, 
create_layer: (name: string, displayOrder: number) => Promise<Layer>, 
create_node: (input: CreateNodeInput) => Promise<Node>, 
delete_edge: (id: string) => Promise<null>, 
get_layers: () => Promise<Layer[]>, 
get_nodes: (layerId: string) => Promise<Node[]>, 
mark_learned: (id: string, learned: boolean) => Promise<Node>, 
seed_sample_data: () => Promise<null>, 
update_node_position: (id: string, x: number, y: number, z: number) => Promise<null>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
